- name: Create Kubernetes Cluster of Awesomeness
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
	 - name: create aquamon cluster
		gcp_container_cluster:
	    name: aquamonCluster
	    initial_node_count: 3
	    master_auth:
	        username: "astein.ny@gmail.com"
	        password: "{{ lookup('env','GCE_PASSWORD') }}"
	  node_config:
	    machine_type: "n1-standard-4"
	    disk_size_gb: 100
	  zone: 'us-central1-a'
	  project: {{ lookup('env','GCE_PROJECT') }}
	  auth_kind: service_account
	  service_account_file: {{ lookup('env','GCE_CREDENTIALS_FILE') }}
	  scopes:
	    - https://www.googleapis.com/auth/cloud-platform
	  state: present
	is.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
	--subnetwork "default" \
